import { DummyProfile } from "@/app/components/common/allImages/AllImages";

export const profiles = [
  {
    id: "1",
    isNew: true,
    verified: true,
    name: "Gabrielle Fiana",
    age: "24",
    height: "160 cm-5Ft",
    occupation: "Sales Manager",
    location: "India",
  },
  {
    id: "2",
    image: DummyProfile,
    isNew: true,
    verified: true,
    name: "John Doe",
    age: "29",
    height: "175 cm-5Ft9",
    occupation: "Software Engineer",
    location: "USA",
  },
  // Add more profiles as needed
];

export const dropdownOptions = [
  { value: "Software Engineer", label: "Software Engineer" },
  { value: "Electrical Engineer", label: "Electrical Engineer" },
  { value: "Electronics Engineer", label: "Electronics Engineer" },
];
export const yesNoOptions = [
  { value: "Yes", label: "Yes" },
  { value: "No", label: "No" },
];
export const castOptions = [
  { value: "Brahmins", label: "Brahmins" },
  { value: "Kshatriyas", label: "Kshatriyas" },
  { value: "Vaishyas", label: "Shudras" },
  { value: "Hyderabad", label: "Hyderabad" },
];
export const religionOptions = [
  { value: "Hinduism", label: "Hinduism" },
  { value: "Islam", label: "Islam" },
  { value: "Christianity", label: "Christianity" },
  { value: "Sikhism", label: "Sikhism" },
  { value: "Buddhism", label: "Buddhism" },
  { value: "Jainism", label: "Jainism" },
  { value: "Zoroastrianism", label: "Zoroastrianism" },
];
export const degreeOptions = [
  { value: "Matric", label: "Matric" },
  { value: "Intermediate", label: "Intermediate" },
  { value: "Bachelors", label: "Bachelors" },
  { value: "Masters", label: "Masters" },
];
export const occupationOptions = [
  { value: "Government Job", label: "Government Job" },
  { value: "Private Job", label: "Private Job" },
  { value: "Business", label: "Business" },
  { value: "Self-Employed", label: "Self-Employed" },
  { value: "Freelancer", label: "Freelancer" },
  { value: "Teacher", label: "Teacher" },
  { value: "Doctor", label: "Doctor" },
  { value: "Engineer", label: "Engineer" },
  { value: "Lawyer", label: "Lawyer" },
  { value: "Banking Professional", label: "Banking Professional" },
  { value: "Defense Services", label: "Defense Services" },
  { value: "Police", label: "Police" },
  { value: "Artist", label: "Artist" },
  { value: "Journalist", label: "Journalist" },
  { value: "Farmer", label: "Farmer" },
  { value: "Social Worker", label: "Social Worker" },
  { value: "Architect", label: "Architect" },
  { value: "Chartered Accountant", label: "Chartered Accountant" },
  { value: "Consultant", label: "Consultant" },
  { value: "Scientist", label: "Scientist" },
  { value: "IT Professional", label: "IT Professional" },
  { value: "Retail Worker", label: "Retail Worker" },
  { value: "Actor", label: "Actor" },
  { value: "Musician", label: "Musician" },
  { value: "Sports Person", label: "Sports Person" },
  { value: "Professor", label: "Professor" },
  { value: "Pharmacist", label: "Pharmacist" },
  { value: "Nurse", label: "Nurse" },
  { value: "Mechanic", label: "Mechanic" },
  { value: "Electrician", label: "Electrician" },
  { value: "Driver", label: "Driver" },
  { value: "Chef", label: "Chef" },
  { value: "Hotel Manager", label: "Hotel Manager" },
  { value: "Entrepreneur", label: "Entrepreneur" },
  { value: "Civil Services", label: "Civil Services" },
  { value: "Clerk", label: "Clerk" },
  { value: "Lab Technician", label: "Lab Technician" },
  { value: "Pilot", label: "Pilot" },
  { value: "Fashion Designer", label: "Fashion Designer" },
];
export const employmentOptions = [
  { value: "Full-Time", label: "Full-Time" },
  { value: "Part-Time", label: "Part-Time" },
  { value: "Self-Employed", label: "Self-Employed" },
  { value: "Freelancer", label: "Freelancer" },
  { value: "Internship", label: "Internship" },
  { value: "Contract", label: "Contract" },
  { value: "Temporary", label: "Temporary" },
  { value: "Casual", label: "Casual" },
  { value: "Remote", label: "Remote" },
  { value: "Apprenticeship", label: "Apprenticeship" },
  { value: "Retired", label: "Retired" },
  { value: "Unemployed", label: "Unemployed" },
];
export const incomeRangeOptions = [
  { value: "Less than 2 LPA", label: "Less than 2 LPA" },
  { value: "2 - 5 LPA", label: "2 - 5 LPA" },
  { value: "5 - 10 LPA", label: "5 - 10 LPA" },
  { value: "10 - 20 LPA", label: "10 - 20 LPA" },
  { value: "20 - 50 LPA", label: "20 - 50 LPA" },
  { value: "50 LPA - 1 Cr", label: "50 LPA - 1 Cr" },
  { value: "More than 1 Cr", label: "More than 1 Cr" },
];
export const ageOptions = [
  { value: "18", label: "18" },
  { value: "19", label: "19" },
  { value: "20", label: "20" },
  { value: "21", label: "21" },
  { value: "22", label: "22" },
  { value: "23", label: "23" },
  { value: "24", label: "24" },
  { value: "25", label: "25" },
  { value: "26", label: "26" },
  { value: "27", label: "27" },
  { value: "28", label: "28" },
  { value: "29", label: "29" },
  { value: "30", label: "30" },
  { value: "31", label: "31" },
  { value: "32", label: "32" },
  { value: "33", label: "33" },
  { value: "34", label: "34" },
  { value: "35", label: "35" },
  { value: "36", label: "36" },
  { value: "37", label: "37" },
  { value: "38", label: "38" },
  { value: "39", label: "39" },
  { value: "40", label: "40" },
  { value: "41", label: "41" },
  { value: "42", label: "42" },
  { value: "43", label: "43" },
  { value: "44", label: "44" },
  { value: "45", label: "45" },
  { value: "46", label: "46" },
  { value: "47", label: "47" },
  { value: "48", label: "48" },
  { value: "49", label: "49" },
  { value: "50", label: "50" },
  { value: "51", label: "51" },
  { value: "52", label: "52" },
  { value: "53", label: "53" },
  { value: "54", label: "54" },
  { value: "55", label: "55" },
  { value: "56", label: "56" },
  { value: "57", label: "57" },
  { value: "58", label: "58" },
  { value: "59", label: "59" },
  { value: "60+", label: "60+" },
];
export const heightOptions = [
  { value: "4'0\"", label: "4'0\"" },
  { value: "4'1\"", label: "4'1\"" },
  { value: "4'2\"", label: "4'2\"" },
  { value: "4'3\"", label: "4'3\"" },
  { value: "4'4\"", label: "4'4\"" },
  { value: "4'5\"", label: "4'5\"" },
  { value: "4'6\"", label: "4'6\"" },
  { value: "4'7\"", label: "4'7\"" },
  { value: "4'8\"", label: "4'8\"" },
  { value: "4'9\"", label: "4'9\"" },
  { value: "4'10\"", label: "4'10\"" },
  { value: "4'11\"", label: "4'11\"" },
  { value: "5'0\"", label: "5'0\"" },
  { value: "5'1\"", label: "5'1\"" },
  { value: "5'2\"", label: "5'2\"" },
  { value: "5'3\"", label: "5'3\"" },
  { value: "5'4\"", label: "5'4\"" },
  { value: "5'5\"", label: "5'5\"" },
  { value: "5'6\"", label: "5'6\"" },
  { value: "5'7\"", label: "5'7\"" },
  { value: "5'8\"", label: "5'8\"" },
  { value: "5'9\"", label: "5'9\"" },
  { value: "5'10\"", label: "5'10\"" },
  { value: "5'11\"", label: "5'11\"" },
  { value: "6'0\"", label: "6'0\"" },
  { value: "6'1\"", label: "6'1\"" },
  { value: "6'2\"", label: "6'2\"" },
  { value: "6'3\"", label: "6'3\"" },
  { value: "6'4\"", label: "6'4\"" },
  { value: "6'5\"", label: "6'5\"" },
  { value: "6'6\"", label: "6'6\"" },
  { value: "6'7\"", label: "6'7\"" },
  { value: "6'8\"", label: "6'8\"" },
  { value: "6'9\"", label: "6'9\"" },
  { value: "6'10\"", label: "6'10\"" },
  { value: "6'11\"", label: "6'11\"" },
  { value: "7'0\"", label: "7'0\"" },
];
export const familyTypeOptions = [
  { value: "Nuclear Family", label: "Nuclear Family" },
  { value: "Joint Family", label: "Joint Family" },
  { value: "Extended Family", label: "Extended Family" },
];
export const familyStatusOptions = [
  { value: "Middle Class", label: "Middle Class" },
  { value: "Upper Middle Class", label: "Upper Middle Class" },
  { value: "Rich", label: "Rich" },
  { value: "Affluent", label: "Affluent" },
];
export const familyValueOptions = [
  { value: "Traditional", label: "Traditional" },
  { value: "Moderate", label: "Moderate" },
  { value: "Liberal", label: "Liberal" },
];
export const foodPreferencesOptions = [
  { value: "Vegetarian", label: "Vegetarian" },
  { value: "Non-Vegetarian", label: "Non-Vegetarian" },
  { value: "Eggetarian", label: "Eggetarian" },
  { value: "Vegan", label: "Vegan" },
  { value: "Jain", label: "Jain" },
];
export const lookingForOptions = [
  { value: "Marriage", label: "Marriage" },
  { value: "Serious Relationship", label: "Serious Relationship" },
  { value: "Friendship", label: "Friendship" },
];
export const physicalStatusOptions = [
  { value: "Normal", label: "Normal" },
  { value: "Physically Challenged", label: "Physically Challenged" },
];
export const motherTongueOptions = [
  { value: "Hindi", label: "Hindi" },
  { value: "Bengali", label: "Bengali" },
  { value: "Telugu", label: "Telugu" },
  { value: "Marathi", label: "Marathi" },
  { value: "Tamil", label: "Tamil" },
  { value: "Urdu", label: "Urdu" },
  { value: "Gujarati", label: "Gujarati" },
  { value: "Malayalam", label: "Malayalam" },
  { value: "Kannada", label: "Kannada" },
  { value: "Odia", label: "Odia" },
  { value: "Punjabi", label: "Punjabi" },
  { value: "Assamese", label: "Assamese" },
  { value: "Maithili", label: "Maithili" },
  { value: "Sindhi", label: "Sindhi" },
  { value: "Konkani", label: "Konkani" },
  { value: "Kashmiri", label: "Kashmiri" },
  { value: "Santhali", label: "Santhali" },
  { value: "Manipuri", label: "Manipuri" },
  { value: "Nepali", label: "Nepali" },
  { value: "Other", label: "Other" },
];
export const manglikOptions = [
  { value: "Manglik", label: "Manglik" },
  { value: "Non-Manglik", label: "Non-Manglik" },
  { value: "Anshik Manglik", label: "Anshik Manglik" },
  { value: "Don't Know", label: "Don't Know" },
];
export const starOptions = [
  { value: "Ashwini", label: "Ashwini" },
  { value: "Bharani", label: "Bharani" },
  { value: "Krittika", label: "Krittika" },
  { value: "Rohini", label: "Rohini" },
  { value: "Mrigashira", label: "Mrigashira" },
  { value: "Ardra", label: "Ardra" },
  { value: "Punarvasu", label: "Punarvasu" },
  { value: "Pushya", label: "Pushya" },
  { value: "Ashlesha", label: "Ashlesha" },
  { value: "Magha", label: "Magha" },
  { value: "Purva Phalguni", label: "Purva Phalguni" },
  { value: "Uttara Phalguni", label: "Uttara Phalguni" },
  { value: "Hasta", label: "Hasta" },
  { value: "Chitra", label: "Chitra" },
  { value: "Swati", label: "Swati" },
  { value: "Vishakha", label: "Vishakha" },
  { value: "Anuradha", label: "Anuradha" },
  { value: "Jyeshtha", label: "Jyeshtha" },
  { value: "Mula", label: "Mula" },
  { value: "Purva Ashadha", label: "Purva Ashadha" },
  { value: "Uttara Ashadha", label: "Uttara Ashadha" },
  { value: "Shravana", label: "Shravana" },
  { value: "Dhanishta", label: "Dhanishta" },
  { value: "Shatabhisha", label: "Shatabhisha" },
  { value: "Purva Bhadrapada", label: "Purva Bhadrapada" },
  { value: "Uttara Bhadrapada", label: "Uttara Bhadrapada" },
  { value: "Revati", label: "Revati" },
];
export const doshOptions = [
  { value: "Kaal Sarp Dosh", label: "Kaal Sarp Dosh" },
  { value: "Mangal Dosh", label: "Mangal Dosh" },
  { value: "Pitra Dosh", label: "Pitra Dosh" },
  { value: "Nadi Dosh", label: "Nadi Dosh" },
  { value: "Bhakoot Dosh", label: "Bhakoot Dosh" },
  { value: "Rajju Dosh", label: "Rajju Dosh" },
  { value: "No Dosh", label: "No Dosh" },
  { value: "Don't Know", label: "Don't Know" },
];
export const stateOptions = [
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
  { value: "Other", label: "Other" },
];
export const cityOptions = [
  { value: "Mumbai", label: "Mumbai" },
  { value: "Delhi", label: "Delhi" },
  { value: "Bangalore", label: "Bangalore" },
  { value: "Hyderabad", label: "Hyderabad" },
  { value: "Chennai", label: "Chennai" },
  { value: "Kolkata", label: "Kolkata" },
  { value: "Ahmedabad", label: "Ahmedabad" },
  { value: "Pune", label: "Pune" },
  { value: "Jaipur", label: "Jaipur" },
  { value: "Lucknow", label: "Lucknow" },
  { value: "Kanpur", label: "Kanpur" },
  { value: "Nagpur", label: "Nagpur" },
  { value: "Indore", label: "Indore" },
  { value: "Bhopal", label: "Bhopal" },
  { value: "Visakhapatnam", label: "Visakhapatnam" },
  { value: "Patna", label: "Patna" },
  { value: "Vadodara", label: "Vadodara" },
  { value: "Ghaziabad", label: "Ghaziabad" },
  { value: "Ludhiana", label: "Ludhiana" },
  { value: "Agra", label: "Agra" },
  { value: "Nashik", label: "Nashik" },
  { value: "Faridabad", label: "Faridabad" },
  { value: "Meerut", label: "Meerut" },
  { value: "Rajkot", label: "Rajkot" },
  { value: "Varanasi", label: "Varanasi" },
  { value: "Srinagar", label: "Srinagar" },
  { value: "Aurangabad", label: "Aurangabad" },
  { value: "Dhanbad", label: "Dhanbad" },
  { value: "Amritsar", label: "Amritsar" },
  { value: "Navi Mumbai", label: "Navi Mumbai" },
  { value: "Allahabad", label: "Allahabad" },
  { value: "Howrah", label: "Howrah" },
  { value: "Ranchi", label: "Ranchi" },
  { value: "Gwalior", label: "Gwalior" },
  { value: "Jabalpur", label: "Jabalpur" },
  { value: "Coimbatore", label: "Coimbatore" },
  { value: "Jodhpur", label: "Jodhpur" },
  { value: "Madurai", label: "Madurai" },
  { value: "Raipur", label: "Raipur" },
  { value: "Kota", label: "Kota" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Guwahati", label: "Guwahati" },
  { value: "Solapur", label: "Solapur" },
  { value: "Hubli-Dharwad", label: "Hubli-Dharwad" },
  { value: "Mysore", label: "Mysore" },
  { value: "Tiruchirappalli", label: "Tiruchirappalli" },
  { value: "Bareilly", label: "Bareilly" },
  { value: "Aligarh", label: "Aligarh" },
  { value: "Moradabad", label: "Moradabad" },
  { value: "Jalandhar", label: "Jalandhar" },
  { value: "Bhubaneswar", label: "Bhubaneswar" },
  { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
  { value: "Salem", label: "Salem" },
  { value: "Bhiwandi", label: "Bhiwandi" },
  { value: "Cuttack", label: "Cuttack" },
  { value: "Firozabad", label: "Firozabad" },
  { value: "Kochi", label: "Kochi" },
  { value: "Bhavnagar", label: "Bhavnagar" },
  { value: "Dehradun", label: "Dehradun" },
  { value: "Durgapur", label: "Durgapur" },
  { value: "Asansol", label: "Asansol" },
  { value: "Nanded", label: "Nanded" },
  { value: "Kolhapur", label: "Kolhapur" },
  { value: "Ajmer", label: "Ajmer" },
  { value: "Gulbarga", label: "Gulbarga" },
  { value: "Jamnagar", label: "Jamnagar" },
  { value: "Ujjain", label: "Ujjain" },
  { value: "Loni", label: "Loni" },
  { value: "Siliguri", label: "Siliguri" },
  { value: "Jhansi", label: "Jhansi" },
  { value: "Ulhasnagar", label: "Ulhasnagar" },
  { value: "Jammu", label: "Jammu" },
  { value: "Sangli", label: "Sangli" },
  { value: "Mangalore", label: "Mangalore" },
  { value: "Erode", label: "Erode" },
  { value: "Belgaum", label: "Belgaum" },
  { value: "Ambattur", label: "Ambattur" },
  { value: "Tirunelveli", label: "Tirunelveli" },
  { value: "Malegaon", label: "Malegaon" },
  { value: "Gaya", label: "Gaya" },
  { value: "Udaipur", label: "Udaipur" },
  { value: "Maheshtala", label: "Maheshtala" },
  { value: "Davanagere", label: "Davanagere" },
  { value: "Kozhikode", label: "Kozhikode" },
  { value: "Akola", label: "Akola" },
  { value: "Kurnool", label: "Kurnool" },
  { value: "Bokaro", label: "Bokaro" },
  { value: "Rajahmundry", label: "Rajahmundry" },
  { value: "South Dumdum", label: "South Dumdum" },
  { value: "Bellary", label: "Bellary" },
  { value: "Patiala", label: "Patiala" },
  { value: "Gopalpur", label: "Gopalpur" },
  { value: "Agartala", label: "Agartala" },
  { value: "Bhagalpur", label: "Bhagalpur" },
  { value: "Muzaffarnagar", label: "Muzaffarnagar" },
  { value: "Bhatpara", label: "Bhatpara" },
  { value: "Panihati", label: "Panihati" },
  { value: "Latur", label: "Latur" },
  { value: "Dhule", label: "Dhule" },
  { value: "Rohtak", label: "Rohtak" },
  { value: "Korba", label: "Korba" },
  { value: "Bhilwara", label: "Bhilwara" },
  { value: "Berhampur", label: "Berhampur" },
  { value: "Muzaffarpur", label: "Muzaffarpur" },
  { value: "Ahmednagar", label: "Ahmednagar" },
  { value: "Mathura", label: "Mathura" },
  { value: "Kollam", label: "Kollam" },
  { value: "Avadi", label: "Avadi" },
  { value: "Kadapa", label: "Kadapa" },
  { value: "Kamarhati", label: "Kamarhati" },
  { value: "Bilaspur", label: "Bilaspur" },
  { value: "Shahjahanpur", label: "Shahjahanpur" },
  { value: "Bijapur", label: "Bijapur" },
  { value: "Rampur", label: "Rampur" },
];
export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
];
export const maritalStatus = [
    { value: "Single", label: "Single" },
    { value: "Married", label: "Married" },
    { value: "Divorced", label: "Divorced" },
  ]