import { PlanItems } from "@/types/landingSectionTypes";

export const plans: PlanItems = [
    {
      title: "Starter",
      price: "₹80",
      period: "/month",
      description: "Lorem ipsum dolor sit amet dolor sit conset cetur adip.",
      features: [
        "3 months Duration",
        "213 Messages",
        "Live Chats",
        "2 Profile Views",
        "Up to 3 team members",
      ],
      featureClr: "text-darkBlue",
      buttonLabel: "Get started",
      bgColor: "bg-white",
      textColor: "text-gray-800",
      priceColor: "text-primary",
      buttonBgColor: "bg-orange-500",
      borderColor: "border-gray",
      buttonTextColor: "text-white",
      variant: "primary",
    },
    {
      title: "Basic",
      price: "₹150",
      period: "/month",
      description: "Lorem ipsum dolor sit amet dolor sit conset cetur adip.",
      features: [
        "3 months Duration",
        "213 Messages",
        "Live Chats",
        "2 Profile Views",
        "Up to 3 team members",
      ],
      featureClr: "text-white",
      buttonLabel: "Get started",
      bgColor: "bg-darkBlue",
      textColor: "text-white",
      priceColor: "text-white",
      buttonBgColor: "bg-white",
      borderColor: "border-white",
      buttonTextColor: "text-orange-900",
      variant: "secondary",
    },
    {
      title: "Premium",
      price: "₹180",
      period: "/month",
      description: "Lorem ipsum dolor sit amet dolor sit conset cetur adip.",
      features: [
        "3 months Duration",
        "213 Messages",
        "Live Chats",
        "2 Profile Views",
        "Up to 3 team members",
      ],
      featureClr: "text-darkBlue",
      buttonLabel: "Get started",
      bgColor: "bg-white",
      textColor: "text-gray-800",
      priceColor: "text-primary",
      buttonBgColor: "bg-orange-500",
      borderColor: "border-gray",
      buttonTextColor: "text-white",
      variant: "primary",
    },
  ];